/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enigma;

import java.awt.CardLayout;
import javax.swing.*;
import java.io.*;
import java.awt.*;

/**
 *
 * @author Abhishek Balam
 */
public class SelectEncryptCipher extends javax.swing.JFrame {

    /**
     * Creates new form SelectEncryptCipher
     */
    
    public SelectEncryptCipher(File Text,int Choice) {
        initComponents();
        choice=Choice;
        txt=Text;
       jLabel1.setText("You Have Chosen to Open: "+Text.getAbsolutePath());
       
       MethodPanel panel1= new MethodPanel("Ceasar Cipher","<html><h1>Julius Ceasar,</h1>In his personal correspondence used a simple<br>"
               + "encryption method to keep his conversations private.<br>This came to be known by his name.</html>",1,this);
       
       MethodPanel panel2= new MethodPanel("Vigenere Cipher","<html>A 16th century French diplomat,<b><i>Blaise de Vigenere</i></b>, "
               + "created a very simple cipher<br> that is moderately difficult for any unintended parties to decipher.<br>"
               + " It is somewhat like a variable Caesar cipher, but the N changed with every letter.<br> You would \"encode\" "
               + "your message with a passphrase, and the letters of your <br>passphrase would determine how each letter in the message would be encrypted.",2,this);
       
       
       MethodPanel panel3= new MethodPanel("Atbash Cipher","hsghdassdsda",3,this);
       
       MethodPanel panel4= new MethodPanel("One Time Pad","hsghdassdsda",4,this);
       
       
       cards = new JPanel(new CardLayout());
       cards.add(panel1,"Ceasar Cipher");
       cards.add(panel2,"Vigenere Cipher");
       cards.add(panel3,"Atbash Cipher");
       cards.add(panel4,"One Time Pad");
       
       
       super.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/container_file.png")).getImage());
       super.setLocationRelativeTo(null);
       super.setVisible(true);
       
    }
    
        public SelectEncryptCipher() {
        
            initComponents();
            
            MethodPanel panel1= new MethodPanel("Caesar Cipher","<html><h1>Julius Ceasar,</h1>In his personal correspondence used a simple<br>"
               + "encryption method to keep his conversations private.<br>This came to be known by his name.</html>",1,this);
       
            MethodPanel panel2= new MethodPanel("Vigenere Cipher","<html>A 16th century French diplomat,<br><b><i>Blaise de Vigenere</i></b>,<br> "
               + "created a very simple cipher<br> that is moderately difficult for any unintended parties to decipher.<br>"
               + " It is somewhat like a variable Caesar cipher, but the N changed with every letter.<br> You would \"encode\" "
               + "your message with a passphrase, and the letters of your <br>passphrase would determine how each letter in the message would be encrypted.",2,this);
       
            MethodPanel panel3= new MethodPanel("Atbash Cipher","hsghdassdsda",3,this);
       
            MethodPanel panel4= new MethodPanel("One Time Pad","hsghdassdsda",4,this);
            
            cards.add(panel1,"Caesar Cipher");
            cards.add(panel2,"Vigenere Cipher");
            cards.add(panel3,"Atbash Cipher");
            cards.add(panel4,"One Time Pad");
       
            super.setLocationRelativeTo(null);
            super.setVisible(true);
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane3 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        cb = new javax.swing.JComboBox();
        cards = new javax.swing.JPanel();
        footerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Encryption Cipher");
        setUndecorated(true);
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });

        jLayeredPane3.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane3.setOpaque(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 3));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        cb.setBackground(new java.awt.Color(51, 51, 51));
        cb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cb.setForeground(new java.awt.Color(0, 51, 255));
        cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Caesar Cipher", "Vigenere Cipher", "Atbash Cipher", "One Time Pad" }));
        cb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        cb.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        cb.setEditor(null);
        cb.setOpaque(false);
        cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbItemStateChanged(evt);
            }
        });
        cb.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cbMouseDragged(evt);
            }
        });
        cb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbMousePressed(evt);
            }
        });

        cards.setOpaque(false);
        cards.setLayout(new java.awt.CardLayout());

        footerPanel.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cards, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane3.add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 600);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ezgif.com-gif-maker.gif"))); // NOI18N
        jLayeredPane3.add(jLabel3);
        jLabel3.setBounds(90, 0, 620, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbItemStateChanged
        // TODO add your handling code here:
            CardLayout cl = (CardLayout)(cards.getLayout());
            cl.show(cards, (String)evt.getItem());
            validate();
            repaint();
    }//GEN-LAST:event_cbItemStateChanged

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        // TODO add your handling code here:
        int notches = evt.getWheelRotation();
        
        o+=notches;
        
        if(o<=-1){
            o=0;
            cb.setSelectedIndex(0);
        }
        else if(o>=(cb.getItemCount())){
            o=cb.getItemCount()-1;
            cb.setSelectedIndex(o);
        }
        else {
            cb.setSelectedIndex(o);
        }
    }//GEN-LAST:event_formMouseWheelMoved

    private void cbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMousePressed
        // TODO add your handling code here:
        initialClick = evt.getPoint();
        getComponentAt(initialClick);
    
    }//GEN-LAST:event_cbMousePressed

    private void cbMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMouseDragged
        // TODO add your handling code here:
                                // get location of Window
        int thisX = getLocation().x;
        int thisY = getLocation().y;

        // Determine how much the mouse moved since the initial click
        int xMoved = (thisX + evt.getX()) - (thisX + initialClick.x);
        int yMoved = (thisY + evt.getY()) - (thisY + initialClick.y);

        // Move window to this position
        int X = thisX + xMoved;
        int Y = thisY + yMoved;
        setLocation(X, Y);
    
    }//GEN-LAST:event_cbMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectEncryptCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectEncryptCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectEncryptCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectEncryptCipher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
          UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
      }
      catch(Exception e){
          throw new RuntimeException(e);
      }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    
   private static int o=0; 
   public File txt;
   public int choice=0;
   private Point initialClick;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cards;
    private javax.swing.JComboBox cb;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
